CPP=g++
###############
agregateStats: agregateStats.cpp
	$(CPP) -o $@ agregateStats.cpp

statsGenerator: statsGenerator.cpp
	$(CPP) -o $@ statsGenerator.cpp

clean:
	rm -f agregateStats statsGenerator
